### ISSUE TITLE
[question] why you invented this template language(pts-lang), what are the benefits?

### ISSUE THREAD

**Issue by liaodalin19903** [petter/pts-lang#3]
Hi,

Could you tell more about  [pts-lang](https://github.com/petter/pts-lang)'s usage? 

why you invented this template language, what are the benefits?

**Comment by petter** [comment]
Hi! 👋🏻 

Package Templates Script (PTS) was a language I developed as part of my master's thesis. In short it was made to experiment with the Package Templates language mechanism (which can be reminiscent of aspect-oriented programming).

Package Templates enables the programmer to bundle a feature into a package, and can later instantiate the bundle inside another package, merging the two. You could for instance create a package for graphs and another for domain knowledge about roads and merge these two to get a model of road networks.

If you are interested in reading more about PTS or the Package Templates language mechanism you can read more about both in my [master's thesis](https://www.duo.uio.no/handle/10852/87098).
